

# swagger配置
swagger:
  # 是否启用swagger，默认：true
  enabled: true
  # 标题
  title: "课程《实用性软件设计》\n数据库SQL文档生成器"
  contact:
    # 维护人
    name: "第二组"
    email: "xxx@qq.com"
    url: "xxx"
  # 版本
  version: "1.0"
  # 描述
  description: "API 描述"
  # swagger扫描的基础包，默认：全扫描
  base-package: "org"
  # 需要处理的基础URL规则，默认：/**
  base-path: /**
  # 需要排除的URL规则，默认：空
  #  exclude-path: ""
  license: "Apache License, Version 2.0"
  license-url: "https://www.apache.org/licenses/LICENSE-2.0.html"


# Knife4j配置
knife4j:
  swagger-ui:
    enabled: true
    path: "/doc.html"

server:
  port: 8888

spring:
  freemarker:
    template-loader-path=classpath: /templates
